name: Build

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Create release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"

      - name: Build Rootless Package
        uses: L1ghtmann/theos-build@main
        with:
          extra_args: THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Build Rootful Package
        uses: L1ghtmann/theos-build@main
        with:
          extra_args: FINALPACKAGE=1

      - name: Attach Packages To Release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release upload "$TAG" packages/*.deb
